services:
  portfolio_app:
    build: .
    container_name: portfolio_app
    expose:
      - "8080"

  caddy_portfolio:
    image: caddy:latest
    container_name: caddy_portfolio
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - portfolio_app

volumes:
  caddy_data:
  caddy_config:

